[package]
name = "garagedb-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "garagedb"
path = "src/main.rs"

[dependencies]
garagedb-core = { path = "../core" }
garagedb-server = { path = "../server" }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
tempfile = "3"
